# Generated by Django 3.0.3 on 2020-03-27 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,9}$'), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')]),
        ),
    ]
