# Generated by Django 3.0.3 on 2020-03-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0002_auto_20200327_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
