# Generated by Django 3.0.3 on 2020-03-27 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0003_auto_20200327_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
