# Generated by Django 3.0.3 on 2020-03-27 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0004_auto_20200327_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
