# Generated by Django 3.0.3 on 2020-03-27 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0005_auto_20200327_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
