# Generated by Django 3.0.3 on 2020-03-27 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0007_auto_20200327_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(max_length=14),
        ),
    ]
