# Generated by Django 3.0.3 on 2020-03-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appControleClientes', '0009_auto_20200327_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGoogleCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('nomeLink', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appControleClientes.Cliente')),
            ],
        ),
    ]
